<template>
    <appLayout title="workshopPage">
        <div class="container mx-auto">
            <loadingBar :isLoading="isLoading" />

            <headerComponent title="Gmod Workshop Generator" description="Quickly generate gmod workshop.dl files." />

            <div class="flex flex-col md:flex-row gap-5">
                <cardComponent :divider="false" class="w-full md:w-1/2">
                    <form @submit.prevent="generateWorkshop">
                        <div class="flex flex-col md:flex-row gap-4">
                            <div class="flex flex-col w-full text-white">
                                <span class="text-sm pl-1 pb-1">Collection Id/Url</span>
                                <input type="text" v-model="workshopID" placeholder="Eg. 285927858" class="border border-borders rounded-md bg-background/75">
                                <button type="submit" class="bg-accent text-white rounded-r-md px-4 py-1 mt-3">Generate</button>
                            </div>
                        </div>
                    </form>
                </cardComponent>

                <cardComponent title="Insructions" class="w-full md:w-1/2">
                    <p>This file will force players to automatically download your workshop collection addons when connecting. Create a file inside of garrysmod/lua/autorun/server called resource.lua and place the generated code there.</p>
                </cardComponent>
            </div>

            <cardComponent title="Generated Code" class="w-full mt-5">
                <template #buttons>
                    <button @click="copyToClipboard" class="bg-green-600 text-white rounded-md px-4 py-1 mt-3">Copy</button>
                    <button @click="downloadFile" class="bg-blue-500 text-white rounded-md px-4 py-1 mt-3">Download</button>
                </template>
                <pre class="bg-background p-5 rounded-md overflow-x-scroll">
                    <code class="text-muted block" v-html="highlightedCode"></code>
                </pre>
            </cardComponent>

        </div>
    </appLayout>
</template>

<script>
import coreService from '@/services/coreService';

export default {
    name: 'workshopPage',
    data() {
        return {
            workshopID: '',
            generatedCode: `--[[\n  Garry's Mod FastDL resource.lua\n  Generated by: ${this.$appUrl}\n  Workshop ID: \n--]]\n\n Enter your Workshop ID/URL above and hit generate`,
            isLoading: false,
        }
    },

    computed: {
        highlightedCode() {
            return this.generatedCode.replace(/resource\.AddWorkshop\( "(\d+)" \)/g, match => {
                const number = match.match(/\d+/)[0];
                return `<span class="text-white">resource.AddWorkshop( <span class="text-blue-500">"${number}"</span> )</span>`;
            });
        },
    },

    methods: {
        async generateWorkshop() {
            this.resetFields();

            if (!this.workshopID) return push.error('Please enter a workshop id.');
            this.isLoading = true;

            try {
                const response = await coreService.generateWorkshop({workshopID: this.workshopID});
                if(response.status !== 200) return push.error(response.message);

                console.log(`[Workshop Generator]: ${response.message}`);

                this.generatedCode = response.code;
                push.success(response.message);
            } catch (error) {
                console.error(error);
                push.error('An error occurred while trying to generate the workshop code.');
            } finally {
                this.isLoading = false;
            }
        },

        async resetFields() {
            this.generatedCode = `--[[\n  Garry's Mod FastDL resource.lua\n  Generated by: ${this.$appUrl}\n  Workshop ID: \n--]]\n\n Enter your Workshop ID/URL above and hit generate`;
        },

        copyToClipboard() {
            navigator.clipboard.writeText(this.generatedCode);
        },

        downloadFile() {
            const element = document.createElement('a');
            const file = new Blob([this.generatedCode], {type: 'text/plain'});
            element.href = URL.createObjectURL(file);
            element.download = 'resource.lua';
            document.body.appendChild(element);
            element.click();
            push.info('File downloaded successfully.');
        }
    }


}
</script>