<template>
    <appLayout title="workshopPage">
        <div class="container mx-auto">
            <loadingBar :isLoading="isLoading" />

            <!-- Header -->
            <div class="flex flex-col py-16 text-center text-white">
                <h1 class="text-5xl font-bold">Gmod Workshop Generator</h1>
                <p class="text-xl pt-2">Quickly generate gmod workshop.dl files.</p>
            </div>

            <!-- Main Content -->
            <div class="flex gap-5">
                <div class="p-5 bg-foreground rounded-md w-1/2">
                    <form @submit.prevent="generateWorkshop">
                        <div class="flex flex-col md:flex-row gap-4">
                            <!-- Workshop Name -->
                            <div class="flex flex-col w-full text-white">
                                <span class="text-sm pl-1 pb-1">Collection Id/Url</span>
                                <input type="text" v-model="workshopID" placeholder="Eg. 285927858" class="border border-borders rounded-md bg-background/75">
                                <button type="submit" class="bg-accent text-white rounded-r-md px-4 py-1 mt-3">Generate</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="p-5 bg-foreground rounded-md w-1/2 text-white">
                    <h1 class="text-2xl">Instructions</h1>
                    <hr class="border-borders my-2">
                    <p>This file will force players to automatically download your workshop collection addons when connecting. Create a file inside of garrysmod/lua/autorun/server called resource.lua and place the generated code there.</p>
                </div>
            </div>

            <!-- Result -->
            <div class="p-5 bg-foreground text-white rounded-md w-full mt-5">
                <div class="flex place-content-between items-center">
                    <h1 class="text-2xl flex gap-6">Generated Code</h1>
                    <div class="text-2xl font-bold" :class="successMessage ? 'text-green-600' : 'text-red-600'">{{ showMessage }}</div>
                    <div v-if="highlightedCode" class="space-x-3 pb-2">
                        <button @click="copyToClipboard" class="bg-green-600 text-white rounded-md px-4 py-1 mt-3">Copy</button>
                        <button @click="downloadFile" class="bg-blue-500 text-white rounded-md px-4 py-1 mt-3">Download</button>
                    </div>
                </div>
                <hr class="border-borders my-2 mb-3">
                <pre class="bg-background p-5 rounded-md">
                    <code class="text-muted block" v-html="highlightedCode"></code>
                </pre>
            </div>

        </div>
    </appLayout>
</template>

<script>
import appLayout from '@/layouts/appLayout.vue';
import coreService from '@/services/coreService';
import loadingBar from '@/components/loadingBar.vue';

export default {
    name: 'workshopPage',
    components: {
        appLayout,
        loadingBar
    },
    data() {
        return {
            workshopID: '',
            generatedCode: `--[[\n  Garry's Mod FastDL resource.lua\n  Generated by: https://tools.chit.sh\n  Workshop ID: \n--]]\n\n Enter your Workshop ID/URL above and hit generate`,
            highlightedCode: '',
            successMessage: '',
            errorMessage: '',
            isLoading: false,
        }
    },

    computed: {
        highlightedCode() {
            return this.generatedCode.replace(/resource\.AddWorkshop\( "(\d+)" \)/g, match => {
                const number = match.match(/\d+/)[0];
                return `<span class="text-white">resource.AddWorkshop( <span class="text-blue-500">"${number}"</span> )</span>`;
            });
        },
        showMessage() { return this.successMessage || this.errorMessage; }
    },

    methods: {
        async generateWorkshop() {
            // Reset messages and initial generated code
            this.successMessage = '';
            this.errorMessage = '';
            this.generatedCode = `--[[\n  Garry's Mod FastDL resource.lua\n  Generated by: https://tools.chit.sh\n  Workshop ID: \n--]]\n\n Enter your Workshop ID/URL above and hit generate`;

            // Validate workshop id and start loading bar
            if (!this.workshopID) return this.errorMessage = 'Please enter a workshop id.';
            this.isLoading = true;

            try {
                const response = await coreService.generateWorkshop({workshopID: this.workshopID});

                if(response.status === 200) {
                    this.successMessage = response.message;
                    this.generatedCode = response.code;
                } else {
                    return this.errorMessage = response.message;
                }
                
            } catch (error) {
                this.errorMessage = error.message;
                console.log(error);
            } finally {
                this.isLoading = false;
            }
        },

        copyToClipboard() {
            navigator.clipboard.writeText(this.generatedCode);
        },

        downloadFile() {
            const element = document.createElement('a');
            const file = new Blob([this.generatedCode], {type: 'text/plain'});
            element.href = URL.createObjectURL(file);
            element.download = 'resource.lua';
            document.body.appendChild(element);
            element.click();
        }
    }


}
</script>