const axios = require('axios');
const cheerio = require('cheerio');

async function generateCode(workshopID) {
    if(!workshopID) return null;

    const URL = `https://steamcommunity.com/sharedfiles/filedetails/?id=${workshopID}`;
    const row = '.collectionChildren > .collectionItem';
    const itemID = `.workshopItem > a`;
    const itemName = `.collectionItemDetails > a:nth-child(1)`;

    const { data } = await axios.get(URL);
    const $ = cheerio.load(data);

    const rows = $(row).map((i, row) => {
        const id = $(row).find(itemID).attr('href').split('=').pop();
        const name = $(row).find(itemName).text();
        return { id, name };
    }).get();

    return rows;
}

exports.generateWorkshop = async (req, res) => {
    let { workshopID } = req.body;

    // Validate Workshop ID
    if (!workshopID) return res.send({status: 400, message: 'Missing required Field'});
    workshopID.includes('steamcommunity.com') ? workshopID = workshopID.split('=').pop() : workshopID;

    // Generate Code
    const items = await generateCode(workshopID);
    if (!items || items.length <= 1) return res.send({status: 400, message: 'Invalid Workshop ID'});

   // Combine Items
    const combinedItems = items.map((item) => `resource.AddWorkshop( "${item.id}" ) -- ${item.name}`).join('\n');
    const addedComment = `--[[\n  Garry's Mod FastDL resource.lua\n  Generated by: https://tools.chit.sh\n  Workshop ID: ${workshopID} \n--]]\n\n`; 
    const finalCode = addedComment + combinedItems;

    return res.send({status: 200, message: 'Generated Successfuly', code: finalCode });
}